<h3>Add Product</h3>
<form method="POST">
    <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" name="name" class="form-control" id="product-name" placeholder="Enter name">
    </div>
    <div class="form-group">
        <label for="Name">Category</label>
        <input type="text" name="category" class="form-control" id="product-category" placeholder="Enter category">
    </div>
    <div class="form-group">
        <label for="Name">Price</label>
        <input type="number" name="price" class="form-control" id="product-price" placeholder="Enter price">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>
