<h3>Editing product id: <?php echo $this->product->getId(); ?></h3>
<form method="POST">
    <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" name="name" class="form-control" id="product-name" placeholder="Enter name" value="<?php echo $this->product->getName(); ?>">
    </div>
    <div class="form-group">
        <label for="Name">Category</label>
        <input type="text" name="category" class="form-control" id="product-category" placeholder="Enter category" value="<?php echo $this->product->getCategory(); ?>">
    </div>
    <div class="form-group">
        <label for="Name">Price</label>
        <input type="number" name="price" class="form-control" id="product-price" placeholder="Enter price" value="<?php echo $this->product->getPrice(); ?>">
    </div>
    <button type="submit" class="btn btn-warning">Edit</button>
</form>
